export {default as LoginPage} from "../Pages/Login"
export {default as RegistrationPage} from "../Pages/Registration"
export {default as LandingPage} from "../Pages/Landing"
export {default as ForgotPassPage} from "../Pages/ForgotPass"
export {default as DashboardPage} from "../Pages/Dashboard"
